name: Main workflow

on:
  push:
    branches:
      - 'master'

jobs:
  build_and_push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@master
      - id: build
        name: Docker build
        run: docker build -t tarocch1/liver .
      - id: login
        name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - id: push
        name: Docker push
        run: docker push tarocch1/liver
